config/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import landing_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', landing_page, name='landing_page'),
    path('users/', include('users.urls')),
]

users/urls.py
from django.urls import path
from .views import RegisterView,LoginView , LogoutView

app_name = 'users'


urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
   
]

places/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator,MinValueValidator




class Place(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    address = models.CharField(max_length=255)


    def __str__(self):
        return self.name
    

class Owner(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    bio=models.CharField()


    def __str__(self):
        return f"{self.first_name} {self.last_name}"
    

class PlaceOwner(models.Model):
    place = models.ForeignKey(Place, on_delete=models.CASCADE)
    owner = models.ForeignKey(Owner, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.place.name} owned by {self.owner}"



class Comment(models.Model):
    coment_text = models.CharField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    place = models.ForeignKey(Place, on_delete=models.CASCADE)
    stars_given = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])


    def __str__(self):
        return f"{self.user} comment to  {self.place.name}"

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth import authenticate


class RegisterForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.fields['password_confirm'] = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model=User
        fields=('username', 'first_name', 'last_name', 'email', 'password')



    def clean_password_confirm(self):
        password=self.cleaned_data['password']
        password_confirm=self.cleaned_data['password_confirm']


        if password!= password_confirm:
            raise forms.ValidationError("Passwordlar bir biriga mos emas")
        
        return password
    
    def clean_username(self):
        username=self.cleaned_data['username']


        if len(username) <5 or len(username) >30:
            raise forms.ValidationError("Username 5 va 30 orasida bolishi lozim")
        

        return username



class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())

    def clean_username(self):
        username=self.cleaned_data['username']


        if len(username) <5 or len(username) >30:
            raise forms.ValidationError("Username 5 va 30 orasida bolishi lozim")
        

        return username
        
   
    

   

config/views.py
from django .shortcuts import render



def landing_page(request):
    return render(request, template_name= 'landing.html')

places/views.py
from django.shortcuts import render

# Create your views here.

users/views.py
from django.shortcuts import render,redirect
from django.views import View
from .forms import RegisterForm,LoginForm
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.mixins import LoginRequiredMixin


class RegisterView(View):

    def get(self, request):

        form=RegisterForm()
        return render(request, template_name= 'users/register.html', context={'form': form})
    



    def post(self, request):
        form=RegisterForm(request.POST)

        if form.is_valid():
            user=form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()

            return redirect('landing_page')


        return render(request, template_name= 'users/register.html', context={'form': form})
    


class LoginView(View):
    def get(self, request):
        form=LoginForm()
        return render(request, template_name= 'users/login.html', context={'form': form})
    


    def post(self, request):
        form=LoginForm(request.POST)
        if form.is_valid():
            username=form.cleaned_data['username']
            password=form.cleaned_data['password']

            user = authenticate(username=username, password=password)

            if user is not None:
                login(request, user) 

                return redirect('landing_page') 
        
        return render(request, template_name= 'users/login.html', context={'form': form})
    


class LogoutView(LoginRequiredMixin,View):
    def get(self, request):

        logout(request)

        return redirect('landing_page')

    

       

templates/landing.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Landing page</title>
</head>
<body>
    <h1>Landing Page</h1>

    <p>
        <a href="{% url 'users:register' %}">Register</a>
    </p>
    <p>
        {% if user.is_authenticated %}
            <a href="{% url 'users:logout' %}">Logout</a>
        {% else %}
            <a href="{% url 'users:login' %}">Login</a>
        {% endif %}
    </p>
</body>
</html>

users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Page</title>
</head>
<body>
    <h1>Login Page</h1>

    <form  method="post">
        {% csrf_token %}
        
        {{form.as_p}}

        <button type="submit">Log in</button>
    </form>
</body>
</html>

users/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register page</title>
</head>
<body>
    <h1>Register page</h1>

    <form  method="post">
        {% csrf_token %}
        
        {{form.as_p}}

        <button type="submit">Register</button>
    </form>
</body>
</html>